name: Refactoring Tools Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'refactoring-tools/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'refactoring-tools/**'
  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
      working-directory: refactoring-tools
    
    - name: Build
      run: dotnet build --no-restore
      working-directory: refactoring-tools
    
    - name: Run tests
      run: dotnet test --no-build --verbosity normal
      working-directory: refactoring-tools