name: Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'refactoring-tools/**'
      - 'modernizer/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'refactoring-tools/**'
      - 'modernizer/**'
  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: refactoring-tools

    - name: Build
      run: dotnet build --no-restore
      working-directory: refactoring-tools

    - name: Run .NET tests
      run: dotnet test RoslynRefactoring --no-build --verbosity normal
      working-directory: refactoring-tools

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.11

    - name: Install Python dependencies
      run: uv sync --dev
      working-directory: modernizer

    - name: Run modernizer tests
      run: uv run bash test.sh
      working-directory: modernizer
